// <auto-generated />
using System;
using IgnitisPowerPlants.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IgnitisPowerPlants.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IgnitisPowerPlants.Domain.Entities.PowerPlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(6,1)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("PowerPlants", t =>
                        {
                            t.HasCheckConstraint("CK_PowerPlants_Owner", "[Owner] LIKE '% %' AND [Owner] NOT LIKE '%  %' AND [Owner] NOT LIKE '%[0-9]%'");

                            t.HasCheckConstraint("CK_PowerPlants_Power", "[Power] >= 0.0 AND [Power] <= 200.0");

                            t.HasCheckConstraint("CK_PowerPlants_ValidFrom_ValidTo", "[ValidTo] IS NULL OR [ValidFrom] < [ValidTo]");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
